import "./index.css";
export const metadata = {
  title: "Happy Anniverary😘",
  description: "Generated by Next.js",
  icons: {
    icon: "pink-heart.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
